services:
  bar:
    image: bar:latest
    depends_on:
      - bar-mongodb
    environment:
      - PORT=80
      - KAFKA_CONTROL_CENTER_URL=kafka-control-center:9021
      - DB_URL=mongodb://root:example@bar-mongodb:27017/
    labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - 'traefik.enable=true'
      # Define the network that should be used
      - 'traefik.docker.network=api'
      # URL to reach this container
      - 'traefik.http.routers.bar.rule=Host(`api.docker.localhost`) && PathPrefix(`/bar`)'
      # Activation of TLS
      - 'traefik.http.routers.bar.tls=true'
      - 'traefik.http.middlewares.bar-stripprefix.stripprefix.prefixes=/bar'
      - 'traefik.http.routers.bar.middlewares=bar-stripprefix@docker'

      # If port is different than 80, use the following service:
      # - "traefik.http.services.<service_name>.loadbalancer.server.port=<port>"
    networks:
      - api
      - bar-db

  bar-mongodb:
    image: arm64v8/mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - api
      - bar-db

  bar-mongo-express:
    depends_on:
      - bar-mongodb
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@bar-mongodb:27017/
    labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - 'traefik.enable=true'
      # Define the network that should be used
      - 'traefik.docker.network=api'
      # URL to reach this container
      - 'traefik.http.routers.bar-mongo-express.rule=Host(`bar-mongodb-express.docker.localhost`)'
      - 'traefik.http.services.bar-mongo-express-service.loadbalancer.server.port=8081'
      # Activation of TLS
      - 'traefik.http.routers.bar.tls=true'
    networks:
      - api
      - bar-db

networks:
  bar-db: {}
